### ISSUE TITLE
make install don't create user and group

### ISSUE THREAD

**Issue by mhalano** [Stebalien/localtime#1]
The make install command should create the user and group for execute the daemon.

**Comment by Stebalien** [comment]
I use systemd's sysusers to create the users. If you are using systemd, install this daemon and reboot; the user and group will be automatically created on boot. If not, just create the username/group yourself. If you want it to work immediately, you need to run `systemd-sysusers $PREFIX/lib/sysusers.d/localtime.conf`.

I don't do this in the Makefile because it makes packaging more painful.

**Comment by mhalano** [comment]
May be a separated shell script? I was looking for systemd-sysusers in Ubuntu 15.10 and can't find the binaries, just the manpages. I think this is not a very universal method to add users and groups for now. May be when Systemd become more mature.

**Comment by Stebalien** [comment]
I've updated the README and added an `install-user` target to the Makefile.
